//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodingProblem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodingProblem()
        {
            this.CodingProblemHints = new HashSet<CodingProblemHint>();
            this.CourseInstanceCodingProblems = new HashSet<CourseInstanceCodingProblem>();
            this.StudentGradables = new HashSet<StudentGradable>();
            this.Submissions = new HashSet<Submission>();
            this.Tests = new HashSet<Test>();
            this.VariableValues = new HashSet<VariableValue>();
            this.CodingProblemInstances = new HashSet<CodingProblemInstance>();
        }
    
        public string Instructions { get; set; }
        public string Script { get; set; }
        public string Solution { get; set; }
        public string ClassName { get; set; }
        public string MethodName { get; set; }
        public string ParameterTypes { get; set; }
        public string Language { get; set; }
        public string TestCaseClass { get; set; }
        public string Before { get; set; }
        public string After { get; set; }
        public int MaxGrade { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public int Attempts { get; set; }
        public bool Active { get; set; }
        public int Role { get; set; }
        public int Id { get; set; }
        public string ExpectedOutput { get; set; }
        public string Parameters { get; set; }
        public string TestCode { get; set; }
        public string TestCodeForStudent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodingProblemHint> CodingProblemHints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseInstanceCodingProblem> CourseInstanceCodingProblems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentGradable> StudentGradables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Submission> Submissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VariableValue> VariableValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodingProblemInstance> CodingProblemInstances { get; set; }
    }
}
