//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodingProblemHint
    {
        public int Id { get; set; }
        public int CodingProblemId { get; set; }
        public bool Reviewed { get; set; }
        public bool Correct { get; set; }
        public string Hint { get; set; }
        public string Solution { get; set; }
        public string StudentAnswer { get; set; }
    
        public virtual CodingProblem CodingProblem { get; set; }
    }
}
