//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInstancePollGroup
    {
        public int CourseInstanceId { get; set; }
        public int ModuleObjectiveId { get; set; }
        public int PollGroupId { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual CourseInstance CourseInstance { get; set; }
        public virtual ModuleObjective ModuleObjective { get; set; }
        public virtual PollGroup PollGroup { get; set; }
    }
}
