//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseCourseMaterialRequirement
    {
        public int x_CourseInstanceId { get; set; }
        public int CourseMaterialRequirementId { get; set; }
        public bool Active { get; set; }
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual CourseMaterialRequirement CourseMaterialRequirement { get; set; }
    }
}
