//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Text { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public int CourseInstanceId { get; set; }
    
        public virtual CourseInstance CourseInstance { get; set; }
        public virtual Student Student { get; set; }
    }
}
