//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeWeight
    {
        public int CourseInstanceId { get; set; }
        public int Id { get; set; }
        public int ActivityWeight { get; set; }
        public int AssessmentWeight { get; set; }
        public int MaterialWeight { get; set; }
        public int DiscussionWeight { get; set; }
        public int PollWeight { get; set; }
        public int MidtermWeight { get; set; }
        public int FinalWeight { get; set; }
    
        public virtual CourseInstance CourseInstance { get; set; }
    }
}
