//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Language()
        {
            this.ErrorParsings = new HashSet<ErrorParsing>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Keywords { get; set; }
        public string KeywordsOutput { get; set; }
        public string Comment { get; set; }
        public string CodeStart { get; set; }
        public string CodeEnd { get; set; }
        public string CompilerDirectory { get; set; }
        public string SourceExtension { get; set; }
        public string Compiler { get; set; }
        public string OutputExtension { get; set; }
        public string CompilationParameters { get; set; }
        public string TestToolDirectory { get; set; }
        public string TestToolExe { get; set; }
        public string OutParameters { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorParsing> ErrorParsings { get; set; }
    }
}
