//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizQuestion()
        {
            this.QuizHints = new HashSet<QuizHint>();
            this.QuizQuestionImages = new HashSet<QuizQuestionImage>();
            this.QuizQuestionRatings = new HashSet<QuizQuestionRating>();
            this.StudentQuizQuestions = new HashSet<StudentQuizQuestion>();
        }
    
        public string Prompt1 { get; set; }
        public string Prompt2 { get; set; }
        public string Answer { get; set; }
        public string Source { get; set; }
        public int MaxGrade { get; set; }
        public bool CaseSensitive { get; set; }
        public int PositionX { get; set; }
        public int PositionY { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public string Type { get; set; }
        public int VideoTimestamp { get; set; }
        public string VideoSource { get; set; }
        public bool EmbedAction { get; set; }
        public int Id { get; set; }
        public int ActivityId1 { get; set; }
        public Nullable<int> ElementStyleId { get; set; }
        public string Images { get; set; }
        public Nullable<int> UsesHint { get; set; }
    
        public virtual Activity Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizHint> QuizHints { get; set; }
        public virtual QuizQuestionElementStyle QuizQuestionElementStyle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizQuestionImage> QuizQuestionImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizQuestionRating> QuizQuestionRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentQuizQuestion> StudentQuizQuestions { get; set; }
    }
}
