//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestionChoice
    {
        public int OptionId { get; set; }
        public int QuestionId { get; set; }
        public string Choice { get; set; }
        public bool Correct { get; set; }
    }
}
