//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLogin
    {
        public int RequestLoginId { get; set; }
        public string SchoolName { get; set; }
        public string CourseName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int ApprovalStatus { get; set; }
    }
}
