//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseAccess
    {
        public int StudentId { get; set; }
        public System.DateTime CourseId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Id { get; set; }
        public int CourseInstanceId { get; set; }
    
        public virtual CourseInstance CourseInstance { get; set; }
        public virtual Student Student { get; set; }
    }
}
