//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLogin
    {
        public int LoginId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime Date { get; set; }
        public string State { get; set; }
        public string IPAddress { get; set; }
    }
}
