//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGradable
    {
        public int StudentId { get; set; }
        public int Grade { get; set; }
        public int MaxGrade { get; set; }
        public int Id { get; set; }
        public Nullable<int> CodingProblemId { get; set; }
        public Nullable<int> CourseInstanceId { get; set; }
    
        public virtual CodingProblem CodingProblem { get; set; }
        public virtual Student Student { get; set; }
    }
}
