//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseInstanceCompletion
    {
        public int StudentId { get; set; }
        public int CourseInstanceId { get; set; }
        public Nullable<int> Assessments { get; set; }
        public Nullable<int> Quizzes { get; set; }
        public Nullable<int> Midterm { get; set; }
        public Nullable<int> Final { get; set; }
        public Nullable<int> Poll { get; set; }
    
        public virtual CourseInstance CourseInstance { get; set; }
        public virtual Student Student { get; set; }
    }
}
