//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Submission()
        {
            this.SubmissionCodeErrors = new HashSet<SubmissionCodeError>();
        }
    
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string Code { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> Grade { get; set; }
        public string History { get; set; }
        public int CodingProblemId { get; set; }
        public Nullable<int> CourseInstanceId { get; set; }
        public string Comment { get; set; }
        public string Error { get; set; }
    
        public virtual CodingProblem CodingProblem { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionCodeError> SubmissionCodeErrors { get; set; }
    }
}
