//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VariableValue()
        {
            this.CodingProblemInstances = new HashSet<CodingProblemInstance>();
        }
    
        public int idVariableValue { get; set; }
        public int CodingProblemId { get; set; }
        public string VarName { get; set; }
        public string possibleValues { get; set; }
    
        public virtual CodingProblem CodingProblem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodingProblemInstance> CodingProblemInstances { get; set; }
    }
}
